# Dependencies
markdown:            redcarpet
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:            Dev Dad
tagline:          'Confessions from a repeat failed Entrepreneur'
description:      'Blog of YourName. Here are some technical stuff. Some notes about development.'
url:              https://devdad10.github.io

author:
  name:           'Dev Dad'
  url:            http://devdad10.github.io
  gravatar:       https://en.gravatar.com/devdad10
  photo:          https://2.gravatar.com/avatar/00000000000000000000000000000000?size=350
  introduction:   'Some introduction words that will be displayed under the avatar. You may include HTML <a href="#">here</a>.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/codinfox/lanyon-codinfox.github.io
